### ISSUE TITLE
你好，大佬！

### ISSUE THREAD

**Issue by zzj2678** [kilvn/IPTV#1]
你好，大佬！我复刻了你的这个IPTV项目后，手动执行工作流，为啥运行失败了啊？我看了一下你比我多了一个页面构建部署的工作流。

**Comment by kilvn** [comment]
我的github actions有页面构建是因为我的github pages配置的是从分支部署。

你fork过去工作流执行失败是因为我在代码中做了限制，只有仓库所有人是我才能运行

**Comment by zzj2678** [comment]
那大佬可以帮我执行工作流吗？或是授权我行吗


zzj
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kilvn/IPTV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kilvn/IPTV] 你好，大佬！ (Issue #1)





 
我的github actions有页面构建是因为我的github pages配置的是从分支部署。
 
你fork过去工作流执行失败是因为我在代码中做了限制，只有仓库所有人是我才能运行

**Comment by zzj2678** [comment]
那我怎么样才能自动更新啊？大佬

**Comment by kilvn** [comment]
> 那我怎么样才能自动更新啊？大佬

我的仓库本来就是自动更新的，每天1、10、17点自动更新，你不需要自己fork一份手动跑

**Comment by zzj2678** [comment]
是IPV4还是IPV6的啊，可以加一下QQ吗？大佬

**Comment by zzj2678** [comment]
我看了一下好像V6的

**Comment by kilvn** [comment]
> 我看了一下好像V6的

央视频道用的[fanmingming/live](https://github.com/fanmingming/live)的源，所以ipv6才可以，其余的v4就可以

**Comment by zzj2678** [comment]
方便加一下QQ吗？大佬

**Comment by zzj2678** [comment]
方便加一下QQ吗？大佬
