### ISSUE TITLE
CHC频道没有了，还有可能增加吗？

### ISSUE THREAD

**Issue by iamxiaojianzheng** [kilvn/IPTV#3]

**Comment by kilvn** [comment]
本来就没有CHC，已新增“电影频道”

**Comment by iamxiaojianzheng** [comment]
![image](https://github.com/user-attachments/assets/456173a4-028c-4776-928a-efe745dd1d97)

我指的chc就是这几个频道，上周末在电视上看 突然没有了。

**Comment by iamxiaojianzheng** [comment]
> 本来就没有CHC，已新增“电影频道”

感谢🙏
